meta_product_name: "Waterfall"
meta_title: "Waterfall · Create Impactful Charts. Simply."
meta_description: "Waterfall is an easy to use chart builder. Make beautiful charts in no time."
meta_image: "laptop-placeholder.png"
# twitter_account: "@product_twitter_account" # required for Twitter Cards
